apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bp2g8k6nz-java-quarkus
  janus-idp.io/tekton: bp2g8k6nz-java-quarkus
  backstage.io/kubernetes-id: bp2g8k6nz-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bp2g8k6nz-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
